version: '3'
services:
  front:
    build:
      context: .
      dockerfile: front/Dockerfile.front
    volumes:
      - ./:/front/src/app # ローカルとコンテナ内の同期
    command: sh -c " yarn start"
    ports:
      - "3000:3000"
    stdin_open: true
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: django-db
      MYSQL_USER: django
      MYSQL_PASSWORD: django
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ./mysql:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d/:ro
    ports:
      - "3306:3306"
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
    command: sh -c "python manage.py runserver 0.0.0.0:8080"
    volumes:
      - ./backend:/backend
    ports:
      - "8080:8080"
    depends_on:
      - db
