FROM python:3.7-alpine
LABEL architecture="shikoku"

ENV PYTHONUNBUFFERED 1

RUN mkdir /backend
WORKDIR /backend
COPY ./backend /backend

COPY ./backend/requirements.txt /requirements.txt
RUN pip install -r /backend/requirements.txt

RUN adduser -D user
USER user
