version: '3'
services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/front/src/app # ローカルとコンテナ内の同期
    command: sh -c "cd front && yarn start"
    ports:
      - "3000:3000"
    stdin_open: true
