FROM python:3.9-slim-buster
LABEL architecture="shikoku"

RUN apt-get update && \
    apt-get -y install gcc libmariadb-dev

ENV PYTHONUNBUFFERED 1

RUN mkdir /backend
WORKDIR /backend

COPY backend/requirements.txt /backend/requirements.txt
RUN pip install -r /backend/requirements.txt

WORKDIR /backend/playlist

RUN adduser user
USER user
